USE  labdata;
DROP TABLE IF EXISTS Grades;
DROP TABLE IF EXISTS course_student;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS Courses;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Teachers;
DROP TABLE IF EXISTS Manager;